chore: update new upstream version
deepin-community/doxygen pull request #1
Opened 2023-07-10 03:36 UTC by xzl01

Log:

2023-07-10 10:09 UTC, UTsweetyfish requested changes

2023-07-10 10:09 UTC, UTsweetyfish commented on debian/patches/0001-avoid-compass.patch
> -===================================================================
这个 header 最好留着吧？

2023-07-11 07:49 UTC, xzl01 commented on debian/patches/0001-avoid-compass.patch
> -===================================================================
严格意义上已经不是同一个patch了，我更改了其应用的位置

2023-07-11 08:31 UTC, UTsweetyfish commented on debian/patches/0001-avoid-compass.patch
> -===================================================================
:ok_hand:

2023-07-11 08:32 UTC, UTsweetyfish commented
```
dpkg-source: error: cannot read doxygen/debian/patches/manpage.diff: No such file or directory
dpkg-source: info: applying manpage.diff
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch 'manpage.diff' is correctly applied by quilt, use 'quilt refresh' to update it
```

2023-07-12 03:33 UTC, UTsweetyfish commented
/lgtm

2023-07-17 07:07 UTC, xzl01 commented
/recheck obs

2023-07-17 07:07 UTC, xzl01 commented
/check obs

2023-07-18 03:24 UTC, Zeno-sole commented
/approve

2023-07-18 03:25 UTC, merged